### ISSUE TITLE
error running groovyclient in a pipe

### ISSUE THREAD

**Issue by rich-coe** [kobo/groovyserv#72]
I'm running a groovy script in a pipe
find . -type f | while read fn ; do groovyclient script.groovy $fn ; done

On processing the very first file I get the following error:
ERROR: could not read headers from server: read tcp 127.0.0.1:37130->127.0.0.1:1961: read: connection reset by peer

The output of the script is incomplete, but varies on how much output is produced.  It does not always fail on the same amount of output.

There errors in the server log
2016/09/08 15:56:58,944 [ERROR](GServThreadGroup:37022:0) (RequestWorker:201) Exception: INTERRUPTED
groovyx.groovyserv.exception.GServInterruptedException: By client request
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at groovyx.groovyserv.StreamRequestHandler.run(StreamRequestHandler.groovy:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
        (sanitized)

and
2016/09/08 15:57:00,915 [ERROR](java.lang.ThreadGroup[name=system,maxpri=10]) (RequestWorker:168) Failed to send the exit status: 5 
groovyx.groovyserv.exception.GServIOException: Failed to send exit status
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at groovyx.groovyserv.ClientConnection.sendExit(ClientConnection.groovy:110)
        at groovyx.groovyserv.ClientConnection.sendExit(ClientConnection.groovy)
        at groovyx.groovyserv.ClientConnection$sendExit$0.call(Unknown Source)
        at groovyx.groovyserv.RequestWorker.closeSafely(RequestWorker.groovy:166)
        at groovyx.groovyserv.RequestWorker.closeSafely(RequestWorker.groovy)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at groovyx.groovyserv.RequestWorker.terminated(RequestWorker.groovy:177)
        at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:704)
        at java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1397)
        at java.util.concurrent.ThreadPoolExecutor.finalize(ThreadPoolExecutor.java:1480)
        at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:101)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:32)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:190)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovyx.groovyserv.ClientConnection$_sendExit_closure1.doCall(ClientConnection.groovy:106)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at groovyx.groovyserv.ClientConnection.sendExit(ClientConnection.groovy:103)
        ... 18 more
        (sanitized)

**Comment by rich-coe** [comment]
It looks like groovyclient is stealing char input from the /dev/tty or changing the terminal char attributes.
I ran 'groovyclient script.groovy | less'
and as I try to type chars into less to search or page, every other character is lost, sometimes have to type the same char more than twice to get it to appear.

**Comment by rich-coe** [comment]
groovyclient is reading all the stdin data from the pipe 
646   read(0, "./20160729/88057955/c3f904fb.dcm"..., 4096) = 4096
646   read(0, "160729/88057955/c88f0519.dcm\n./2"..., 4092) = 4092
646   read(0, "160729/88057955/af5b0486.dcm\n./2"..., 4092) = 4092
646   read(0, "160729/88057955/8c9d03c8.dcm\n./2"..., 4092) = 4092
646   read(0, "160729/88057955/7e4d0378.dcm\n./2"..., 4092) = 2603

**Comment by rich-coe** [comment]
Aha, seems like a permanent restriction.  You cannot operate a 'groovyclient' program in a pipeline.
The program reads all stdin and passes it to the server process, whether or not the groovy program is reading stdin.

**Comment by nobeans** [comment]
I'm sorry for too late response because the notification was off...

> The program reads all stdin and passes it to the server process, whether or not the groovy program is reading stdin.

Right. It's a "permanent restriction".
