### ISSUE TITLE
GroovyServ not working on JDK 21 and Groovy 4

### ISSUE THREAD

**Issue by lprimak** [kobo/groovyserv#90]
Hi,

Any chance to update groovyserv/client to modern Java / Groovy please?
Currently, groovyserv fails to start up:
```
% groovyclient my 
Java home directory: /Users/lprimak/.sdkman/candidates/java/current
Groovy home directory: /Users/lprimak/.sdkman/candidates/groovy/current
Groovy command path: /Users/lprimak/.sdkman/candidates/groovy/current/bin/groovy (found at GROOVY_HOME)
GroovyServ home directory: /Users/lprimak/.sdkman/candidates/groovyserv/1.2.0
GroovyServ work directory: /Users/lprimak/.groovy/groovyserv
Original classpath: (none)
GroovyServ default classpath: /Users/lprimak/.sdkman/candidates/groovyserv/1.2.0/lib/*
Starting server........................................................................................................
ERROR: timed out while waiting for server startup
```

Log file:
```
2023/10/29 01:58:11,467 [ERROR] (java.lang.ThreadGroup[name=main,maxpri=10]) (GroovyServer:61) Unexpected error: GroovyServer
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:429)
        at groovyx.groovyserv.GroovyServer.setupSecurityManager(GroovyServer.groovy:85)
        at groovyx.groovyserv.GroovyServer.start(GroovyServer.groovy:48)
        at groovyx.groovyserv.GroovyServer.main(GroovyServer.groovy:154)
        at script_from_command_line.run(script_from_command_line:1)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:287)
        at groovy.lang.GroovyShell.run(GroovyShell.java:393)
        at groovy.lang.GroovyShell.run(GroovyShell.java:382)
        at groovy.ui.GroovyMain.processOnce(GroovyMain.java:649)
        at groovy.ui.GroovyMain.run(GroovyMain.java:389)
        at groovy.ui.GroovyMain.access$1400(GroovyMain.java:67)
        at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:313)
        at groovy.ui.GroovyMain.processArgs(GroovyMain.java:141)
        at groovy.ui.GroovyMain.main(GroovyMain.java:114)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        (sanitized)
```

Thank you.

**Comment by maximus-omnia** [comment]
It is still the same issue.

Environment (SDKMAN):

- Using java version 21.0.6-tem in this shell.
- Using groovy version 4.0.25 in this shell.
- Using groovyserv version 1.2.0 in this shell.

Error messages:

```
2025/01/30 19:10:28,934 [ERROR] (java.lang.ThreadGroup[name=main,maxpri=10]) (GroovyServer:61) Unexpected error: GroovyServer
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:430)
        at groovyx.groovyserv.GroovyServer.setupSecurityManager(GroovyServer.groovy:85)
        at groovyx.groovyserv.GroovyServer.start(GroovyServer.groovy:48)
        at groovyx.groovyserv.GroovyServer.main(GroovyServer.groovy:154)
        at script_from_command_line.run(script_from_command_line:1)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:287)
        at groovy.lang.GroovyShell.run(GroovyShell.java:393)
        at groovy.lang.GroovyShell.run(GroovyShell.java:382)
        at groovy.ui.GroovyMain.processOnce(GroovyMain.java:649)
        at groovy.ui.GroovyMain.run(GroovyMain.java:389)
        at groovy.ui.GroovyMain.access$1400(GroovyMain.java:67)
        at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:313)
        at groovy.ui.GroovyMain.processArgs(GroovyMain.java:141)
        at groovy.ui.GroovyMain.main(GroovyMain.java:114)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        (sanitized)

```

**Comment by zebalu** [comment]
Hi!
I don't know, if the project is still alive or not, it is possible that nobody is going to accept my pull request, but you can have a workaround:

When you start the server it copies your `JAVA_OPTS` environment variable, so if you start the server with an env var:
`JAVA_OPTS="-Djava.security.manager=allow"` 
the server is able to start on Java 21 or later.

**Comment by lprimak** [comment]
Thank you for the hint, it does "do stuff" :)

Unfortunately there are other issues.
Although the server now starts, it doesn't "do anything"

```
JAVA_OPTS="-Djava.security.manager=allow" groovyclient -v
GroovyServ Version: Client: 1.2.0
```

It's supposed to print Java and GroovyServer version, but it doesn't

**Comment by lprimak** [comment]
On my mac, the error message is as follows:
```
2025/04/17 16:16:38,260 [ERROR] (GServThreadGroup:63362:1) (RequestWorker:205) Unexpected error
java.lang.UnsatisfiedLinkError: /private/var/folders/97/v3vhvcks5wncyqx3l5g8k22w0000gp/T/jna-381131964/jna10666625079121956547.tmp: dlopen(/private/var/folders/97/v3vhvcks5wncyqx3l5g8k22w0000gp/T/jna-381131964/jna10666625079121956547.tmp, 0x0001): tried: '/private/var/folders/97/v3vhvcks5wncyqx3l5g8k22w0000gp/T/jna-381131964/jna10666625079121956547.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/97/v3vhvcks5wncyqx3l5g8k22w0000gp/T/jna-381131964/jna10666625079121956547.tmp' (no such file), '/private/var/folders/97/v3vhvcks5wncyqx3l5g8k22w0000gp/T/jna-381131964/jna10666625079121956547.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2402)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2028)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:382)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:370)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
	at groovyx.groovyserv.platform.PlatformMethods.<clinit>(PlatformMethods.groovy:35)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:382)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:370)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
	at groovyx.groovyserv.platform.GlobalCurrentDir.setDir(GlobalCurrentDir.groovy:43)
	at groovyx.groovyserv.GroovyInvokeHandler.run(GroovyInvokeHandler.groovy:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
	(sanitized)
```

**Comment by lprimak** [comment]
Success! I was able to get it to work by replacing `.sdkman/candidates/groovyserv/current/lib/jna-4.2.2.jar` with
an updated version, `jna-5.16.0.jar` in my instance

**Comment by zebalu** [comment]
You are absolutely right. This was enough to get it work on Linux, but the same issue happens on Windows. Replacing JNA is a solution. I am going to create a pull request for that as well, and I hope they are going to respond. :)
Thank you!
